[proxy]
key_list = exec "/usr/share/ovirt-engine/libexec/ovirt-vmconsole-proxy-helper/ovirt-vmconsole-list.py" --version "{version}" keys
console_list = exec "/usr/share/ovirt-engine/libexec/ovirt-vmconsole-proxy-helper/ovirt-vmconsole-list.py" --version "{version}" consoles --entityid "{entityid}"
